### ISSUE TITLE
The global setting for autoplay sound is wrongly reset after a browser restart

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [alastor0325/autoplay-shield-study#11]
**[Affected versions]:**
- Firefox Beta Unbranded 63.0b8

**[Affected Platforms]:** 	 	
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have the following prefs:
	- `shieldStudy.logLevel` to `All`
	- `extensions.fastblock_shield_mozilla_org.test.variationName` to `block`
	- `extensions.legacy.enabled` to `true`
	- `xpinstall.signatures.required` to `false`
- The Block-autoplay add-on is installed.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Navigate to "about:preferences#privacy" and scroll down to "Permissions" section.
3. Select the "Allow autoplay" option for global autoplay.
4. Restart the browser.
5. Observe the setting for global autoplay.

**[Expected result]:**
- "Allow autoplay" option is set for global autoplay.

**[Actual result]:**
- "Don't Autoplay" option is set for global autoplay.

**[Notes]:**
- This issue is reproducible on all other branches.
- This issue is also reproducible if the "Always ask" option is selected.
- Attached a screen recording of the issue: 

![globalsettings](https://user-images.githubusercontent.com/40061643/46027696-28470c00-c0f7-11e8-9779-d52774a0c616.gif)

**Comment by alastor0325** [comment]
Thank for reporting! Fixed by https://github.com/alastor0325/autoplay-shield-study/commit/995dd3286df3ae659985a899936ceda691b47849.

**Comment by Softvision-RemusDranca** [comment]
I have verified this issue using the latest Block Autoplay (2.0.0-signed) version and the issue is no longer reproducible. Tested on Windows 10 x64, Mac 10.13 and Ubuntu 18.04 x64.
