### ISSUE TITLE
The "Remember this decision" checkbox is checked after a Browser Restart in the "allow-and-notRemember" branch

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [alastor0325/autoplay-shield-study#12]
**[Affected versions]:**
- Firefox Beta 63.0b9

**[Affected Platforms]:** 	 	
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have the following prefs:
	- `shieldStudy.logLevel` to `All`
	- `extensions.fastblock_shield_mozilla_org.test.variationName` to `allow-and-notRemember`.
- The Block-autoplay add-on is installed.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Navigate to https://edition.cnn.com/videos.
3. Observe the checkbox in the Block-autoplay doorhanger.
4. Restart the browser and navigate to https://edition.cnn.com/videos. 
5. Observe the checkbox in the Block-autoplay doorhanger.

**[Expected result]:**
- Step 3 and Step 5: The checkbox is unchecked.

**[Actual result]:**
- Step 3: The checkbox is unchecked.
- Step 5: The checkbox is checked.

**[Notes]:**
- The issue is reproducible if you navigate on other websites with auto-play videos.
- This issue is also reproducible if one of the Block-autoplay doorhanger option is selected: "Allow Autoplay" or "Don't Allow".
- Attached is a screen recording of the issue: 

![restart](https://user-images.githubusercontent.com/40061643/46217291-40629980-c34a-11e8-9a41-d49f30e91407.gif)

**Comment by alastor0325** [comment]
Thank you! Fixed by https://github.com/alastor0325/autoplay-shield-study/commit/15ddfdb9de3f505428a8386b481636b87dcabdc6.

**Comment by Softvision-RemusDranca** [comment]
I have verified this issue using the latest Block Autoplay (2.0.0 - 10/1/2018) version and the issue is no longer reproducible. Tested on Windows 10 x64, Mac 10.13 and Ubuntu 18.04 x64.
