### ISSUE TITLE
Clicking the "Allow" button on the doorhanger after waiting 10 seconds doesn't play videos on CNN and DailyMotion

### ISSUE THREAD

**Issue by Softvision-PatriciuPop** [alastor0325/autoplay-shield-study#13]
[Affected versions]:
- Firefox Beta, Version 63.0b10, Build ID 20180927143327
- Firefox Nightly, Version 64.0a1, Build ID 20180930220130

[Affected Platforms]:
- All Windows
- All Linux
- All Mac

[Prerequisites]:
- extensions.autoplay-shield-study_shield_mozilla_org.test.variationName string pref is set to allow-and-notRemember.
- Autoplay Shield study version 2.0.0 addon is installed.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Navigate to https://www.cnn.com/videos and wait for the page to load.
3. Wait for 10 seconds until a "play" icon is displayed on the video.
4. Click the "Allow" button from the doorhanger and observe the behavior.

[Expected result]:
- The doorhanger is dismissed and the video starts playing.

[Actual result]:
- The doorhanger is dismissed and the video does not start playing.

[Additional Notes]:
- This issue is reproducible on both allow-and-notRemember and allow-and-remember branches.
- This issue is not reproducible on the following sites: YouTube, Yahoo, Twitch, Aol, MSNBC, Today.
- I have attached a screen recording of the issue:
![10 sec](https://user-images.githubusercontent.com/40393891/46288061-38466c00-c58d-11e8-960e-9acfcaf8de6c.gif)

**Comment by alastor0325** [comment]
This is known situaition. Click `allow` doesn't mean the video would start playing, it just gives the site permission to autoplay afterward. In this case, CNN stopped their video before user interact with the doorhanger. Even you have allowed the site to autoplay, but there is not anything can be played.
