### ISSUE TITLE
The doorhanger is not dismissed when navigating to a different non-audio page of the same domain

### ISSUE THREAD

**Issue by Softvision-AndreeaCupsa** [alastor0325/autoplay-shield-study#14]
**[Affected versions]:**
- Beta Unbranded  63.0b10 

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have the following prefs:
    - extensions.fastblock_shield_mozilla_org.test.variationName to one of the following values: allow-and-remember.
    - xpinstall.signatures.required to false.
- The Block-autoplay add-on is installed.

**[Steps to reproduce]:**
1. Open the Firefox browser with the profile from the prerequisites.
2. Navigate to https://twitch.tv.
3. Click on the "Browse" button from the same domain.
4. Observe the left of the address bar area.

**[Expected result]:**
- The doorhanger is dismissed.

**[Actual results]:**
- The doorhanger is still displayed.

**[Notes]:**
- This issue is reproducible also on allow-and-notRemember branch, and on block and control branches after the "Always ask" option is set for the global autoplay seting.
- This issue is reproducible on youtube.com, cnn.com, bbc.com and probably on other website too.
- Attached a screen recording with the issue:

![twitch](https://user-images.githubusercontent.com/37875464/46293708-fc1b0780-c59c-11e8-96a0-b6e6b1510d08.gif)

**Comment by alastor0325** [comment]
In our design, doorhanger will dismiss when 
(1) user press `escape` 
(2) user interacts with doorhanger
(3) user ignores doorhanger and directly play audible video from the page
(4) user navigates to other different document.

In this case, Twitch uses in-document navigation, which is a technique to use same document for presenting different URL. Therefore, the doorhanger won't dismiss unless any of above condition happens.

**Comment by Softvision-AndreeaCupsa** [comment]
Because the doorhanger is not dismissed when navigating on the same domain, I have found the following scenario:

**[Steps to reproduce]:**
1. Open the Firefox browser with the profile from the prerequisites.
2. Navigate to https://twitch.tv.
3. Click on one of the feature games thumbnail, then click on another video.
4. Observe the left of the address bar area and the video from the page.

**[Actual results]:**
- The video automatically starts playing and the doorhanger is dismissed.

Further navigation on the same domain during the same session will no longer trigger the doorhanger and videos will automatically start to play without the user having taken any action on the doorhanger.

Which should be the correct behavior in this situation?

**Comment by alastor0325** [comment]
Yes, it's correct behavior. You have activated the document (by clicking), so the site has already been allowed to autoplay afterward. When the audible video starts playing, the doorhanger will dismiss.
