### ISSUE TITLE
The doorhanger is wrongly dismissed when you click inside the page on several websites

### ISSUE THREAD

**Issue by Softvision-PatriciuPop** [alastor0325/autoplay-shield-study#15]
[Affected versions]:
- Firefox Beta, Version 63.0b10, Build ID 20180927143327
- Firefox Nightly, Version 64.0a1, Build ID 20180930220130

[Affected Platforms]:
- All Windows
- All Linux
- All Mac

[Prerequisites]:
- extensions.autoplay-shield-study_shield_mozilla_org.test.variationName string pref is set to allow-and-notRemember.
- Autoplay Shield study version 2.0.0 addon is installed.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Navigate to https://www.cnn.com/videos and wait for the page to load.
3. Click on the page's background and observe the behavior.

[Expected result]:
- The doorhanger is displayed and the video does not start playing.

[Actual result]:
- The doorhanger is dismissed and the video starts playing.

[Additional Notes]:
- This issue is reproducible on both allow-and-notRemember and allow-and-remember branches.
- This issue is reproducible on the following sites: CNN, BBC, DailyMotion, YouTube, Yahoo video search, Twitch.
- I have attached a screen recording of the issue:
![dismiss](https://user-images.githubusercontent.com/40393891/46347448-3d222300-c654-11e8-857e-b7be54ef9488.gif)

**Comment by alastor0325** [comment]
It's same as https://github.com/alastor0325/autoplay-shield-study/issues/14#issue-365482005.
This is correct behavior, you have activated CNN by clicking, so they have been allowed to autoplay. When the audible video starts playing, the doorhanger will dismiss.
