### ISSUE TITLE
The doorhanger is wrongly dismissed on YouTube when you click specific player buttons.

### ISSUE THREAD

**Issue by Softvision-PatriciuPop** [alastor0325/autoplay-shield-study#16]
[Affected versions]:
- Firefox Beta, Version 63.0b10, Build ID 20180927143327
- Firefox Nightly, Version 64.0a1, Build ID 20181001220118

[Affected Platforms]:
- All Windows
- All Linux
- All Mac

[Prerequisites]:
- extensions.autoplay-shield-study_shield_mozilla_org.test.variationName string pref is set to allow-and-notRemember.
- Autoplay Shield study version 2.0.0 addon is installed.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Navigate to https://www.youtube.com/ and open a video in a new tab.
3. Click the "Theatre mode" button and observe the behavior.

[Expected result]:
- The video enters theatre mode and does not start playing.

[Actual result]:
- The doorhanger is dismissed and the video starts playing as the video enters theatre mode.

[Additional Notes]:
- This issue is reproducible on both allow-and-notRemember and allow-and-remember branches.
- This issue is reproducible on the following YouTube player buttons: "Theatre mode", "Miniplayer" and changing the video quality from the settings.
- This issue is not reproducible on the following YouTube player buttons: "Mute" and volume, "Autoplay", "Annotations", "Speed", "Fullscreen".
- I have attached a screen recording of the issue: [link](https://drive.google.com/open?id=137YX1ZGe9QADGAKXEu8D_4WEMmhzFn6E)

**Comment by alastor0325** [comment]
Same issue as https://github.com/alastor0325/autoplay-shield-study/issues/14 and https://github.com/alastor0325/autoplay-shield-study/issues/15.

**Comment by alastor0325** [comment]
@Softvision-PatriciuPop @Softvision-AndreeaCupsa When you're testing the doorhanger, you can compare behaviors with and without extension, so that you can know whether behaviors are caused by extension.

**Comment by alastor0325** [comment]
This one, #14 and #15 are all the original behaviors of door hanger in our design.
