### ISSUE TITLE
The "totalBlockedAudibleMedia" ping's property value does not increase on Release Candidate 63

### ISSUE THREAD

**Issue by Softvision-AndreeaCupsa** [alastor0325/autoplay-shield-study#18]
**[Affected versions]:**
- Firefox Release Candidate 63.0

**[Affected Platforms]:**
- All Windows
- All Linux
- All Mac

**[Prerequisites]:**
- extensions.autoplay-shield-study_shield_mozilla_org.test.variationName string pref is set any variation branch.
- Autoplay [Shield study version 2.0.1 addon](https://bugzilla.mozilla.org/show_bug.cgi?id=1475099#c28) is installed.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Navigate to a couple websites with audible media.
3. Restart the browser and navigate to the "about:telemetry" page.
4. Observe the "block-autoplay" archived counts ping.

**[Expected result]:**
- The "totalBlockedAudibleMedia" ping's value is increased.

**[Actual result]:**
- The "totalBlockedAudibleMedia" ping's value is "0".

**[Additional Notes]:**
- This issue is reproducible on all study branches.
- This issue is not reproducible on Firefox Beta and Firefox Nightly. 
- I have attached a [screen recording](https://drive.google.com/open?id=1FjL5kJfYk_W6rIrGMDf3_DY-L_sOX3aN) of the issue.

**Comment by alastor0325** [comment]
Fixed in [bug1499803](https://bugzilla.mozilla.org/show_bug.cgi?id=1499803).
