### ISSUE TITLE
Provide endings survey

### ISSUE THREAD

**Issue by alastor0325** [alastor0325/autoplay-shield-study#2]
We need to provide ending survey for user when the the testing end in order to know how do they feel about blocking autoplay.

**Comment by jtg567** [comment]
Typically our team (Shield/Strategy & Insight) will collaborate with yours to deliver the survey experience.

Here's how another team recently provided info to the addon utils for routing survey responses depending on study outcomes - we need to give different UXs to users who complete the study vs. opt out, etc. https://github.com/mozilla/blurts-addon/blob/6282a6e6e659377514c50c2093a212850fdb3203/src/background.js#L87 Note that there's more possible endings than this.

**Comment by alastor0325** [comment]
@jtg567 Thank you for the information! 
How do I submit my survey to the mozilla server once I finish designing my survey?
Thank you!

**Comment by jtg567** [comment]
Of course, @alastor0325 - you're welcome!

If you have an idea of what questions you want to ask you can share them here or in a google doc.

We will review them and work them into the standard Shield study exit funnel when we deploy via SurveyGizmo.

**Comment by alastor0325** [comment]
Hi, @jtg567, Could you help me to review our [survey](https://qsurvey.mozilla.com/collab/video-autoplay-survey)? Thank you!

**Comment by alastor0325** [comment]
the person who helps us to design the survey told me that they have their own review process for survey, so I would close this issue.

In addition, I've add the survey url in my extenion in https://github.com/alastor0325/autoplay-shield-study/pull/3/commits/f199519abd120dd67c81841b461d936104d5a30b, although the survey's content would still have a chance to be changed, depending on the review result of PHD.
