### ISSUE TITLE
The "Learn more" button is missing from the "allow-and-remember" and "allow-and-notRemember" branches' doorhanger

### ISSUE THREAD

**Issue by Softvision-AndreeaCupsa** [alastor0325/autoplay-shield-study#7]
**[Affected versions]:**
- Firefox Beta Unbranded 63.0b7

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have the following prefs:
	- shieldStudy.logLevel to All
	- extensions.fastblock_shield_mozilla_org.test.variationName to allow-and-remember
	- extensions.legacy.enabled to true
	- xpinstall.signatures.required to false
- The Block-autoplay add-on is installed.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Navigate to https://www.twitch.tv.
3. Observe the block autoplay doorhanger.

**[Expected result]:**
- A "Learn more" hyperlink is displayed below the "Will you allow <website> to autoplay media with sound?" text.

**[Actual results]:**
- There is no "Learn more" hyperlink displayed below the "Will you allow <website> to autoplay media with sound?" text.

 **[Notes]:**
- This issue is also reproducible on the "allow-and-notRemember" branch.
- Based on the mock-ups from the Block-autoplay [PHD](https://docs.google.com/document/d/19enwHXxFmK1Bd71AHLeoEt4qDDpBFjsABJ2qEqHEj9g/edit)
- Attached a screen recording of the issue:

![rec of the issue - learn more missing](https://user-images.githubusercontent.com/37875464/45886731-88ba0e80-bdc2-11e8-8b6f-9af47a85f633.gif)

**Comment by alastor0325** [comment]
Thank for reporting! Fixed by https://github.com/alastor0325/autoplay-shield-study/commit/54e866802278ed2aa8eff862a02826b075f138eb.
