### ISSUE TITLE
The "Undo" option is wrongly displayed after the "Block-autoplay" shield study is removed

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [alastor0325/autoplay-shield-study#8]
**[Affected versions]:**
- Firefox Beta Unbranded 63.0b8

**[Affected Platforms]:** 	 	
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have the following prefs:
      - shieldStudy.logLevel to All;
      - extensions.fastblock_shield_mozilla_org.test.variationName to one of the following values: control, block, allow-and-remember or allow-and-notRemember;
      - extensions.legacy.enabled to true;
      - xpinstall.signatures.required to false.
- The Block-autoplay add-on is installed.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Navigate to "about:addons>Extensions" and click the "Block-autoplay" add-on.
3. Click the "Remove" button and observe the behavior.

**[Expected result]:**
- The "Block-autoplay" shield study is uninstalled.

**[Actual result]:**
- The "Undo" button is displayed.

**[Notes]:**
- After the "Undo" button is clicked, the "install" and "enter" pings are sent again.
- Added a screen recording the issue:

![remove](https://user-images.githubusercontent.com/40061643/45960472-fcf3ec80-c024-11e8-8355-4ed526b4973e.gif)

**Comment by alastor0325** [comment]
Same as https://github.com/alastor0325/autoplay-shield-study/issues/9, you can't disable or remove the shield-study extension in `about:addon`.
